[tool.poetry]
name = "goodreads-scraper"
version = "0.1.0"
description = ""
authors = ["karlwebstersponge <19327709+ktasper@users.noreply.github.com>"]
readme = "README.md"
packages = [{include = "goodreads_scraper", from = "src"}]

[tool.poetry.dependencies]
python = "^3.10"
beautifulsoup4 = "^4.11.1"
argparse = "^1.4.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
hello = "src.goodreads_scraper.main:main"